# .github/workflows/deploy.yml
name: Build and Deploy Jekyll site to GitHub Pages

on:
  push:
    branches:
      - main # Or whichever branch you push to

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v4

      - name: Setup Ruby âœ¨
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1' # Choose a Ruby version compatible with your Jekyll
          bundler-cache: true # Automatically runs bundle install and caches gems

      - name: Build site ğŸ”§
        run: bundle exec jekyll build # Build the site into the _site directory
        env:
          JEKYLL_ENV: production

      - name: Setup Pages âš™ï¸
        id: pages
        uses: actions/configure-pages@v5

      - name: Upload artifact â¬†ï¸
        uses: actions/upload-pages-artifact@v3
        # Default path is _site

      - name: Deploy to GitHub Pages ğŸš€
        id: deployment
        uses: actions/deploy-pages@v4
        # Requires configure-pages and upload-pages-artifact steps above